[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
fs_permissions = [{ access = "read", path = "./out" }]

remappings = [
	"forge-std/=lib/forge-std/src/",
	"@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
	"@uniswap/v4-periphery/=lib/v4-periphery/",
	"reactive-lib/=lib/reactive-lib/src/"
]

[fmt]
line_length = 120
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
